name: Trigger Docker Hub

on:
  schedule:
  - cron: "0 5 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Trigger Dockerhub
      run: curl -X POST ${{ secrets.HUB_TRIGGER_URL }}
