name: Trigger Docker Hub

on:
  schedule:
  - cron: "0 20 * * 6"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Trigger Dockerhub (master)
      run: curl -X POST ${{ secrets.HUB_TRIGGER_URL }}
    - name: Trigger Dockerhub (2.0)
      run: curl -X POST -d '{"source_type":"Branch","source_name":"2.0"}' ${{ secrets.HUB_TRIGGER_URL }}
